[web]
servera ansible_host=192.168.50.85

[db]
serverb ansible_host=192.168.50.65

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_become=true
ansible_become_method=sudo
