---
# Galaxy collections required by this project.
collections:
  - name: ansible.posix
    version: ">=1.5.0,<2.0.0"
  - name: community.mysql
    version: ">=3.5.0,<4.0.0"
  - name: community.general
    version: ">=7.0.0,<9.0.0"
  - name: community.crypto
    version: ">=2.0.0,<3.0.0"
